export interface MesActMultired {
  EJE_CHANCE: number
  VTM_CHANCE: number
  EJE_PAGAMAS: number
  VTM_PAGAMAS: number
  EJE_PAGATODO: number
  VTM_PAGATODO: number
  EJE_GANE5: number
  VTM_GANE5: number
  EJE_PATA_MILLONARIA: number
  VTM_PATA_MILLONARIA: number
  EJE_DOBLECHANCE: number
  VTM_DOBLECHANCE: number
  EJE_CHANCE_MILLONARIO: number
  VTM_CHANCE_MILLONARIO: number
  EJE_ASTRO: number
  VTM_ASTRO: number
  EJE_LOTERIA_FISICA: number
  VTM_LOTERIA_FISICA: number
  EJE_LOTERIA_VIRTUAL: number
  VTM_LOTERIA_VIRTUAL: number
  EJE_BETPLAY: number
  VTM_BETPLAY: number
  EJE_GIROS: number
  VTM_GIROS: number
  EJE_SOAT: number
  VTM_SOAT: number
  EJE_RECAUDOS: number
  VTM_RECAUDOS: number
  EJE_RECARGAS: number
  VTM_RECARGAS: number
  EJE_RASPE: number
  VTM_RASPE: number
}